#!/usr/bin/env python3
"""build_firmware.py - builds the firmware (.bin) with the Squirrel! code FROZEN into it.

Put this file in the folder that holds the app's .py files and run it there:

    python3 build_firmware.py --check          # look at the machine and the sources, change nothing
    python3 build_firmware.py --install-idf    # once, if there is no ESP-IDF 5.4.x: clone + install v5.4.2 (needs a network)
    python3 build_firmware.py --setup          # once: submodules, patches, mpy-cross, littlefs (needs quilt and a network)
    python3 build_firmware.py --stage-only     # collect the sources and check them with mpy-cross; no firmware
    python3 build_firmware.py                  # `make pack`  ->  dist/squirrel-<board>-<git>-<time>.bin  (a complete image)
    python3 build_firmware.py --target build   # only the application (micropython.bin): not flashable on its own
    python3 build_firmware.py --flash /dev/ttyACM0   # ... and flash it (only a complete image, at 0x0)
    python3 build_firmware.py --flash-image dist/squirrel-....bin [--flash /dev/ttyACM0]   # flash an image that is already built
    python3 build_firmware.py --build-mpy-cross  # only gcc + make needed (no ESP-IDF, no quilt): builds the repo's mpy-cross
    python3 build_firmware.py --mpy            # no firmware: compile every module to .mpy in dist/mpy/ (a quick relief for RAM)
    python3 build_firmware.py --update-repo    # pull the latest changes in vendor/cardputer-adv-micropython
    python3 build_firmware.py --reset-deps     # forget the resolved ESP-IDF component versions (dependencies.lock, managed_components)
    python3 build_firmware.py --diagnose       # explain the last failed build from its log (.build/make.log)
    python3 build_firmware.py --clean          # remove what this tool generated

What it does, in order:
  1. ensures vendor/cardputer-adv-micropython exists (clones it automatically on first run);
  2. collects the app's sources (every .py here, `screens/` as a package; a flat folder is fine too: the screen
     modules are recognised by how the code imports them); leaves out tests, tools, archive, verify_device.py ...
  3. checks that every module the code imports exists and compiles with the SAME mpy-cross as the firmware;
  4. writes sq_info.py (build id, file list) into the set;
  5. makes a derived board  <base board>_Squirrel  inside the firmware repo: a copy of the base board whose manifest.py
     gets one more line, freeze("$(BOARD_DIR)/squirrel").  Nothing that exists in the repo is modified;
  6. puts the font (fonts/squirrel.vlw or squirrel.vlw) into the image's system file system: it is copied to
     m5stack/fs/system/common/font/ for the time of `make` and removed afterwards, and the device finds it at
     /system/common/font/squirrel.vlw (that partition is written by every flash, so the font cannot get lost);
  7. runs  make BOARD=<derived board> build  with the ESP-IDF environment loaded, finds the image and says
     whether it is a complete one (flash at 0x0).

Settings: command line, or build_config.json next to this file ({"repo": ..., "idf": ..., "base_board": ...}),
or the environment (SQUIRREL_FW_REPO, SQUIRREL_IDF).  Standard library only.
"""
import argparse
import ast
import glob
import json
import os
import re
import shutil
import subprocess
import sys
import time
import zlib

HERE = os.path.dirname(os.path.abspath(__file__))
STATE = os.path.join(HERE, ".build")
DIST = os.path.join(HERE, "dist")
DEFAULT_REPO = os.path.join(HERE, "vendor", "cardputer-adv-micropython")
FIRMWARE_REPO_URL = "https://github.com/TheRealHaoLiu/cardputer-adv-micropython"
DEFAULT_BASE_BOARD = "M5STACK_CardputerADV_Custom"
BOARD_SUFFIX = "_Squirrel"
GENERATED_MARK = ".squirrel_generated"
FONT_NAME = "squirrel.vlw"
FONT_IN_REPO = ("m5stack", "fs", "system", "common", "font")      # packed into fs-system.bin ...
FONT_ON_DEVICE = "/system/common/font/" + FONT_NAME               # ... and found here on the device


def find_font(app_dir):
    """The app's .vlw font: fonts/squirrel.vlw, or squirrel.vlw next to the sources.  None if there is none."""
    for path in (os.path.join(app_dir, "fonts", FONT_NAME), os.path.join(app_dir, FONT_NAME)):
        if os.path.isfile(path):
            return path
    return None
MANIFEST_BEGIN = "# --- Squirrel! (generated by build_firmware.py - do not edit below) ---"

# never frozen: this tool, the launcher that lives on the flash, helper scripts
EXCLUDE_FILES = {"build_firmware.py", "verify_device.py", "main.py", "main_flash.py", "setup.py", "conftest.py",
                 "vlw.py", "make_vlw.py", "check_vlw.py"}          # the last three make the font on the PC (they need PIL)
IDF_WANTED = "v5.4.2"
IDF_URL = "https://github.com/espressif/esp-idf.git"
# Python modules that exist on a PC only: a file importing one of them is a PC-side script, not device code
PC_ONLY = set("PIL fontTools numpy subprocess argparse shutil glob pathlib tempfile unittest pytest tkinter".split())
EXCLUDE_DIRS = {"tools", "archive", "fonts", "device", "tests", "test", "dist", "firmware", "docs", "vendor",
                "__pycache__", ".git", ".build", ".idea", ".vscode", "venv", ".venv"}
# modules that exist in the firmware or in MicroPython itself (an import of anything else that is not in the
# sources is only a warning: we cannot list every module of the firmware)
KNOWN_RUNTIME = set("""sys os time gc json math struct machine micropython network esp esp32 random binascii errno io
collections array select socket ssl _thread asyncio uasyncio ntptime utime ujson ubinascii usb bluetooth framebuf
neopixel hashlib cryptolib deflate re heapq uctypes zlib btree vfs platform ucollections urandom ustruct usys
M5 hardware unit module widgets mrequests requests umqtt aioble lvgl lv_utils m5ui m5utils driver usb_device
display uos uio utime_ nvs cmath""".split())


class BuildError(Exception):
    pass


def say(msg=""):
    print(msg, flush=True)


# ----------------------------------------------------------------------------------------------- firmware repo clone

def ensure_repo(repo, update=False):
    """Clone the firmware repo into vendor/ if it is not there yet; with update=True, pull instead."""
    if os.path.isdir(os.path.join(repo, ".git")):
        if update:
            say(f"updating firmware repo at {repo}")
            code = subprocess.call(["git", "-C", repo, "pull", "--ff-only"])
            if code != 0:
                raise BuildError("git pull failed — check your network or resolve conflicts manually")
        else:
            say(f"firmware repo present at {repo} (use --update-repo to pull latest changes)")
        return
    parent = os.path.dirname(repo)
    os.makedirs(parent, exist_ok=True)
    say(f"cloning firmware repo into {repo} ...")
    say(f"  (first time only; ~100 MB; Ctrl-C is safe: run again to continue)")
    code = subprocess.call(["git", "clone", "--depth", "1", FIRMWARE_REPO_URL, repo])
    if code != 0:
        raise BuildError(
            f"git clone failed. Check your network connection and try again.\n"
            f"  Source : {FIRMWARE_REPO_URL}\n"
            f"  Target : {repo}\n"
            f"  Or set a different path with --repo, SQUIRREL_FW_REPO, or build_config.json."
        )
    say("clone done")


# ----------------------------------------------------------------------------------------------- sources

def find_sources(app_dir, extra_exclude=()):
    """[(relative path with '/', absolute path)] of every .py to freeze (extra_exclude: file names or relative paths to leave out)."""
    found = []
    for root, dirs, files in os.walk(app_dir):
        dirs[:] = sorted(d for d in dirs if d not in EXCLUDE_DIRS and not d.startswith("."))
        for name in sorted(files):
            if not name.endswith(".py") or name.startswith("test_") or name in EXCLUDE_FILES and root == app_dir:
                continue
            absolute = os.path.join(root, name)
            relative = os.path.relpath(absolute, app_dir).replace(os.sep, "/")
            if relative in extra_exclude or name in extra_exclude:
                continue
            found.append((relative, absolute))
    return found


_SCREEN_IMPORT = re.compile(r"""(?:^|\n)\s*(?:from|import)\s+screens\.(\w+)""")
_SCREEN_STRING = re.compile(r"""["']screens\.(\w+)["']""")


def screen_modules(sources):
    """Names X for which the code uses  screens.X  (an import, or a module name in a table of lazy screens)."""
    names = set()
    for _rel, absolute in sources:
        with open(absolute, encoding="utf-8") as f:
            text = f.read()
        names.update(_SCREEN_IMPORT.findall(text))
        names.update(_SCREEN_STRING.findall(text))
    return names


def _same_file(a, b):
    try:
        with open(a, "rb") as fa, open(b, "rb") as fb:
            return fa.read() == fb.read()
    except OSError:
        return False


def _describe(path):
    st = os.stat(path)
    return f"{path}  ({st.st_size} bytes, {time.strftime('%Y-%m-%d %H:%M:%S', time.localtime(st.st_mtime))})"


def layout_for_firmware(sources, prefer=None):
    """The same sources with the screens in a `screens/` package, whatever the folder looks like.

    A screen present BOTH flat and in screens/: identical copies are fine; different copies are an error (one of them
    is stale and it is not for a program to guess which) unless prefer is 'newer', 'flat' or 'screens'.
    Returns ({staged path: absolute path}, [warnings])."""
    wanted = screen_modules(sources)
    staged, warnings, dup = {}, [], {}
    by_rel = dict(sources)
    for rel, absolute in sources:
        base = rel.rsplit("/", 1)[-1][:-3]
        if "/" not in rel and base in wanted:
            target = "screens/" + base + ".py"
            if target in by_rel:
                dup[target] = (absolute, by_rel[target])
                continue
            staged[target] = absolute
        else:
            staged[rel] = absolute
    conflicts = []
    for target, (flat, nested) in sorted(dup.items()):
        if _same_file(flat, nested):
            staged[target] = nested
        elif prefer == "flat":
            staged[target] = flat
            warnings.append(f"{target[8:]} exists flat and in screens/ with DIFFERENT content: using the flat one (--prefer flat)")
        elif prefer == "screens":
            staged[target] = nested
            warnings.append(f"{target[8:]} exists flat and in screens/ with DIFFERENT content: using screens/ (--prefer screens)")
        elif prefer == "newer":
            newer = flat if os.path.getmtime(flat) >= os.path.getmtime(nested) else nested
            staged[target] = newer
            warnings.append(f"{target[8:]} exists flat and in screens/ with DIFFERENT content: using the newer, {newer}")
        else:
            conflicts.append(f"  {target[8:]} exists twice with different content:\n    flat   : {_describe(flat)}\n    screens: {_describe(nested)}")
    if conflicts:
        raise BuildError("Two different copies of the same screen module - one is stale, and the firmware must not freeze the wrong one:\n"
                         + "\n".join(conflicts) + "\n  Delete the stale file, or pass  --prefer newer|flat|screens.")
    for name in sorted(wanted):
        if "screens/" + name + ".py" not in staged:
            warnings.append(f"the code imports screens.{name}, but there is no {name}.py")
    return staged, warnings


def local_top_levels(staged):
    return {p.split("/")[0][:-3] if "/" not in p else p.split("/")[0] for p in staged}


def check_imports(staged):
    """([errors], [warnings]) from reading every import in the sources."""
    errors, warnings = [], []
    local = local_top_levels(staged) | {"sq_info"}        # sq_info.py is generated by this tool
    for rel, absolute in sorted(staged.items()):
        with open(absolute, encoding="utf-8") as f:
            text = f.read()
        try:
            tree = ast.parse(text, rel)
        except SyntaxError as e:
            errors.append(f"{rel}:{e.lineno}: {e.msg}")
            continue
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                names = [a.name for a in node.names]
            elif isinstance(node, ast.ImportFrom) and node.level == 0 and node.module:
                names = [node.module]
            else:
                continue
            for dotted in names:
                top = dotted.split(".")[0]
                if top == "screens":
                    sub = dotted.split(".")[1] if "." in dotted else None
                    if sub and "screens/" + sub + ".py" not in staged:
                        errors.append(f"{rel}:{node.lineno}: imports {dotted}, which is not in the sources")
                elif top in PC_ONLY:
                    errors.append(f"{rel}:{node.lineno}: imports '{top}', which exists on a PC only - this looks like a PC-side script, "
                                  f"not device code. Leave it out: \"exclude\": [\"{rel.rsplit('/', 1)[-1]}\"] in build_config.json, or --exclude")
                elif top not in local and top not in KNOWN_RUNTIME:
                    warnings.append(f"{rel}:{node.lineno}: imports '{top}' - not in the sources, not a known firmware module")
    return errors, sorted(set(warnings))


# ----------------------------------------------------------------------------------------------- stage

SQ_INFO = '''# sq_info.py - what is frozen into this firmware (generated by build_firmware.py)
#   import sq_info; sq_info.report()
BUILD = {build!r}
GIT = {git!r}
FONT_SIZE = {font_size!r}
FILES = {files!r}          # (module file, size, crc32 of the source)


def report():
    import os
    print("Squirrel! build", BUILD, "git", GIT or "-", "|", len(FILES), "frozen modules")
    names = set()
    for entry in FILES:
        names.add(entry[0])
    problems = 0
    folders = []
    for d in (os.getcwd(), "/flash", "/flash/apps/Squirrel", "/lib"):
        if d not in folders:
            folders.append(d)
    for d in folders:
        for sub in ("", "/screens", "/hw"):
            try:
                listing = os.listdir(d.rstrip("/") + sub)
            except OSError:
                continue
            for n in listing:
                base, _dot, ext = n.rpartition(".")
                if ext in ("py", "mpy") and ((sub[1:] + "/" if sub else "") + base + ".py") in names:
                    print("  HIDES a frozen module (found first):", d.rstrip("/") + sub + "/" + n)
                    problems += 1
    try:
        os.stat("/flash/DEV")
        print("  DEV mode is ON (/flash/DEV): files in /flash/apps/Squirrel replace the frozen modules")
    except OSError:
        pass
    try:
        with open("/flash/main.py") as f:
            if "squirrel_boot" not in f.read():
                print("  /flash/main.py does not start squirrel_boot")
                problems += 1
    except OSError:
        print("  /flash/main.py is missing")
        problems += 1
    for path in ("/system/common/font/squirrel.vlw", "/flash/fonts/squirrel.vlw", "/flash/apps/Squirrel/fonts/squirrel.vlw", "/sd/Squirrel/fonts/squirrel.vlw"):
        try:
            size = os.stat(path)[6]
            print("  font:", path, size, "bytes", "(ok)" if not FONT_SIZE or size == FONT_SIZE else "(expected %d)" % FONT_SIZE)
            break
        except OSError:
            pass
    else:
        print("  font: none (only needed for the Polish letters)")
    try:
        import nuts
        origin = getattr(nuts, "__file__", "") or ""
        print("  nuts.py is loaded from:", origin or "?", "(frozen)" if not origin.startswith("/") else "(a FILE: not frozen)")
    except ImportError as e:
        print("  cannot import nuts:", e)
        problems += 1
    print("OK" if not problems else "%d problem(s)" % problems)
'''


def git_short(path):
    try:
        out = subprocess.run(["git", "-C", path, "rev-parse", "--short", "HEAD"], capture_output=True, text=True, timeout=10)
        return out.stdout.strip() if out.returncode == 0 else ""
    except (OSError, subprocess.SubprocessError):
        return ""


def stage(staged, stage_dir, build_id, app_dir):
    """Copy the sources into stage_dir (fresh), add screens/__init__.py and sq_info.py. Returns the file list."""
    if os.path.isdir(stage_dir):
        shutil.rmtree(stage_dir)
    os.makedirs(stage_dir)
    files = []
    for rel, absolute in sorted(staged.items()):
        target = os.path.join(stage_dir, *rel.split("/"))
        os.makedirs(os.path.dirname(target), exist_ok=True)
        shutil.copyfile(absolute, target)
        with open(absolute, "rb") as f:
            data = f.read()
        files.append((rel, len(data), zlib.crc32(data) & 0xFFFFFFFF))
    if any(rel.startswith("screens/") for rel in staged):        # a frozen package needs its __init__.py
        init = os.path.join(stage_dir, "screens", "__init__.py")
        if not os.path.exists(init):
            open(init, "w").close()
    font = find_font(app_dir)
    info = SQ_INFO.format(build=build_id, git=git_short(app_dir), files=tuple(files),
                          font_size=os.path.getsize(font) if font else 0)
    with open(os.path.join(stage_dir, "sq_info.py"), "w", encoding="utf-8") as f:
        f.write(info)
    return files


# ----------------------------------------------------------------------------------------------- firmware repo

def locate_repo(path):
    path = os.path.abspath(os.path.expanduser(path))
    makefile = os.path.join(path, "m5stack", "Makefile")
    boards = os.path.join(path, "m5stack", "boards")
    if not os.path.isfile(makefile) or not os.path.isdir(boards):
        raise BuildError(f"{path} does not look like the firmware repository (no m5stack/Makefile and m5stack/boards).\n"
                         f"  Give the right one with --repo, SQUIRREL_FW_REPO or build_config.json.")
    return path


def idf_candidates(repo, given=None):
    """Folders with an export.sh that could be an ESP-IDF, the explicitly named one first."""
    def ex(p):
        return os.path.abspath(os.path.expanduser(p))
    raw = []
    if given:
        raw.append(given)
    else:
        raw += [os.environ.get("SQUIRREL_IDF"), os.environ.get("IDF_PATH")]
        for base in (os.path.join(repo, ".."), os.path.join(repo, "..", ".."), repo, "~", "~/esp", "~/src"):
            raw += sorted(glob.glob(os.path.join(ex(base), "esp-idf*")))
        raw += sorted(glob.glob(ex("~/esp/*/esp-idf")))
    out = []
    for r in raw:
        if r and os.path.isfile(os.path.join(ex(r), "export.sh")) and ex(r) not in out:
            out.append(ex(r))
    return out


def idf_version(idf):
    try:
        with open(os.path.join(idf, "version.txt")) as f:
            return f.read().strip()
    except OSError:
        pass
    try:
        out = subprocess.run(["git", "-C", idf, "describe", "--tags"], capture_output=True, text=True, timeout=10)
        return out.stdout.strip() if out.returncode == 0 else ""
    except (OSError, subprocess.SubprocessError):
        return ""


def idf_ok(version):
    """ESP-IDF 5.4.x only: this firmware is built and patched for it (and on 5.5 the board's microphone returns silence)."""
    m = re.match(r"v?(\d+)\.(\d+)", version or "")
    return bool(m) and (int(m.group(1)), int(m.group(2))) == (5, 4)


def choose_idf(repo, given=None, allow_any=False):
    """(path, version) of the ESP-IDF to use. Raises BuildError if there is no 5.4.x (unless allow_any)."""
    found = [(p, idf_version(p)) for p in idf_candidates(repo, given)]
    good = [f for f in found if idf_ok(f[1])]
    if good:
        return good[0]
    if allow_any and found:
        say(f"  warning: using ESP-IDF {found[0][1] or '?'} although 5.4.x is expected (--allow-any-idf)")
        return found[0]
    if found:
        listing = "\n".join(f"    {p}  {v or '(version unknown)'}" for p, v in found)
        raise BuildError("No ESP-IDF 5.4.x found. This firmware is built (and its patches are made) for 5.4.2. Found:\n" + listing
                         + "\n  Install the right one next to it:  python3 build_firmware.py --install-idf\n"
                         + "  (or by hand: " + f"git clone --depth 1 --branch {IDF_WANTED} {IDF_URL}; git submodule update --init --recursive; ./install.sh esp32s3)")
    raise BuildError("ESP-IDF not found" + (f" at {given}" if given else "") + ". Install v5.4.2:  python3 build_firmware.py --install-idf\n"
                     "  or point to an existing 5.4.x with --idf /path/to/esp-idf (the folder with export.sh).")


def board_type(makefile_path, board):
    """The BOARD_TYPE the firmware's Makefile gives a board (its `boards :=` list: `M5STACK_CardputerADV:cardputeradv`), or None."""
    try:
        with open(makefile_path, encoding="utf-8") as f:
            text = f.read()
    except OSError:
        return None
    m = re.search(r"^[ \t]*" + re.escape(board) + r":([\w\-]+)[ \t]*\\?[ \t]*$", text, re.M)
    return m.group(1) if m else None


def find_mpy_cross(repo):
    for rel in (("micropython", "mpy-cross", "build", "mpy-cross"), ("micropython", "mpy-cross", "mpy-cross")):
        p = os.path.join(repo, *rel)
        if os.path.isfile(p) and os.access(p, os.X_OK):
            return p
    return shutil.which("mpy-cross")


def compile_check(mpy_cross, stage_dir, keep_dir=None):
    """Compile every staged file with the firmware's own mpy-cross. Returns ([errors], total .mpy bytes)."""
    errors, total = [], 0
    work = keep_dir or os.path.join(STATE, "mpy_check")
    if os.path.isdir(work):
        shutil.rmtree(work)
    for root, _dirs, files in os.walk(stage_dir):
        for name in sorted(files):
            if not name.endswith(".py"):
                continue
            src = os.path.join(root, name)
            rel = os.path.relpath(src, stage_dir)
            out = os.path.join(work, rel[:-3] + ".mpy")
            os.makedirs(os.path.dirname(out), exist_ok=True)
            res = subprocess.run([mpy_cross, "-o", out, "-s", rel, src], capture_output=True, text=True)
            if res.returncode != 0:
                errors.append(f"{rel}: {(res.stderr or res.stdout).strip()[:300]}")
            elif os.path.exists(out):
                total += os.path.getsize(out)
    return errors, total


def make_board(repo, base, new, stage_dir):
    """Create m5stack/boards/<new> as a copy of <base> + the frozen sources. Never touches an existing, foreign board."""
    boards = os.path.join(repo, "m5stack", "boards")
    src, dst = os.path.join(boards, base), os.path.join(boards, new)
    if not os.path.isdir(src):
        raise BuildError(f"base board {base} not found in {boards}\n  Available: {', '.join(sorted(os.listdir(boards))[:12])} ...")
    manifest_src = os.path.join(src, "manifest.py")
    if not os.path.isfile(manifest_src):
        raise BuildError(f"{manifest_src} does not exist - this tool needs a board with its own manifest.py")
    if os.path.exists(dst):
        if not os.path.exists(os.path.join(dst, GENERATED_MARK)):
            raise BuildError(f"{dst} exists and was not made by this tool - not touching it. Pick another --board name.")
        shutil.rmtree(dst)
    shutil.copytree(src, dst, ignore=shutil.ignore_patterns("__pycache__", "*.pyc", "build*"))
    for root, _dirs, files in os.walk(dst):
        for name in files:
            if name.endswith(".py"):
                continue
            path = os.path.join(root, name)
            try:
                with open(path, encoding="utf-8") as f:
                    text = f.read()
            except (UnicodeDecodeError, OSError):
                continue
            if base in text:
                with open(path, "w", encoding="utf-8") as f:
                    f.write(text.replace(base, new))
    shutil.copytree(stage_dir, os.path.join(dst, "squirrel"), ignore=shutil.ignore_patterns("__pycache__", "*.pyc"))
    manifest = os.path.join(dst, "manifest.py")
    with open(manifest, encoding="utf-8") as f:
        text = f.read()
    text = text.rstrip("\n") + "\n\n" + MANIFEST_BEGIN + '\nfreeze("$(BOARD_DIR)/squirrel")\n'
    with open(manifest, "w", encoding="utf-8") as f:
        f.write(text)
    with open(os.path.join(dst, GENERATED_MARK), "w") as f:
        f.write("generated by build_firmware.py\n")
    return dst


def expand_vars(text, repo, board_dir):
    if repo:
        text = (text.replace("$(MPY_DIR)", os.path.join(repo, "micropython"))
                    .replace("$(MPY_LIB_DIR)", os.path.join(repo, "micropython", "lib", "micropython-lib"))
                    .replace("$(PORT_DIR)", os.path.join(repo, "micropython", "ports", "esp32")))
    return text.replace("$(BOARD_DIR)", board_dir)


def manifest_refs(board_dir, repo=None):
    """[(name as written, absolute path)] of the .py files a board's manifest.py names."""
    try:
        with open(os.path.join(board_dir, "manifest.py"), encoding="utf-8") as f:
            text = f.read().split(MANIFEST_BEGIN)[0]
    except OSError:
        return []
    out = []
    for line in text.split("\n"):
        if line.strip().startswith("#"):
            continue
        strings = re.findall(r"""["']([^"']+)["']""", line)
        m = re.search(r"""base_path\s*=\s*["']([^"']+)["']""", line)
        base = m.group(1) if m else None
        if base is not None:
            pairs = [(base, x) for x in strings if x != base and x.endswith((".py", ".mpy"))]
        elif line.strip().startswith("freeze(") and len(strings) >= 2:
            pairs = [(strings[0], x) for x in strings[1:] if x.endswith((".py", ".mpy"))]
        else:
            pairs = [("", x) for x in strings if x.endswith((".py", ".mpy"))]
        for folder, name in pairs:
            path = expand_vars(os.path.join(folder, name) if folder else name, repo, board_dir)
            if "$(" in path:
                continue
            if not os.path.isabs(path):
                path = os.path.join(board_dir, path)
            out.append((name, os.path.normpath(path)))
    return out


def manifest_missing_refs(board_dir, repo=None):
    seen, missing = set(), []
    for name, path in manifest_refs(board_dir, repo):
        if not os.path.exists(path) and path not in seen:
            seen.add(path)
            missing.append((name, path))
    return missing


def manifest_missing_files(board_dir, repo=None):
    return [name for name, _path in manifest_missing_refs(board_dir, repo)]


def makefile_target_for(text, rel):
    variables = {m.group(1) for m in re.finditer(r"^[ \t]*(\w+)[ \t]*[:?+]?=[ \t]*" + re.escape(rel) + r"[ \t]*$", text, re.M)}
    needles = {rel} | {"$(%s)" % v for v in variables} | {"${%s}" % v for v in variables}
    if re.search(r"^" + re.escape(rel) + r"[ \t]*:(?![=:])", text, re.M):
        return rel
    target = None
    for line in text.split("\n"):
        if line.startswith("\t"):
            if target and any(re.search(r"(?:>>?|\btouch\b|\btee\b(?:\s+-a)?|\s-o|--output(?:=|\s))\s*['\"]?" + re.escape(n), line) for n in needles):
                return target
            continue
        m = re.match(r"^([A-Za-z0-9_.\-]+)[ \t]*:(?![=:])", line)
        if m:
            target = m.group(1)
        elif line.strip() and not re.match(r"^[ \t]*(ifeq|ifneq|ifdef|ifndef|else|endif|#)", line):
            target = None
    return None


def generate_missing(repo, base, idf, type_arg=""):
    m5 = os.path.join(repo, "m5stack")
    base_dir = os.path.join(m5, "boards", base)
    made, failed, elsewhere = [], [], []
    try:
        with open(os.path.join(m5, "Makefile"), encoding="utf-8") as f:
            makefile = f.read()
    except OSError:
        makefile = ""
    for name, path in manifest_missing_refs(base_dir, repo):
        if not path.startswith(base_dir + os.sep):
            elsewhere.append(name)
            continue
        rel = os.path.relpath(path, m5)
        target = makefile_target_for(makefile, rel) or rel
        how = "a rule for the file" if target == rel else f"the target `{target}`, whose recipe writes it - and only for BOARD={base}"
        say(f"  {name} is named by the manifest of {base} and does not exist yet: asking the Makefile to make it  (make {target}: {how})")
        code = bash(idf_prefix(idf) + f"make BOARD={base}{type_arg} {target}", cwd=m5)
        (made if code == 0 and os.path.exists(path) else failed).append(name)
    return made, failed, elsewhere


def git_exclude(repo, new):
    path = os.path.join(repo, ".git", "info", "exclude")
    line = f"m5stack/boards/{new}/"
    try:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        existing = open(path, encoding="utf-8").read() if os.path.exists(path) else ""
        if line not in existing.split("\n"):
            with open(path, "a", encoding="utf-8") as f:
                f.write(("" if existing.endswith("\n") or not existing else "\n") + line + "\n")
            return True
    except OSError:
        pass
    return False


# ----------------------------------------------------------------------------------------------- running make

def clean_env():
    env = {k: v for k, v in os.environ.items() if not k.startswith(("IDF_", "ESP_IDF", "OPENOCD_"))}
    env["PATH"] = os.pathsep.join(p for p in env.get("PATH", "").split(os.pathsep) if ".espressif" not in p and "esp-idf" not in p)
    return env


def bash(script, cwd=None):
    say("  $ " + script.replace("\n", " ; ")[:300])
    return subprocess.call(["bash", "-c", script], cwd=cwd, env=clean_env())


def idf_prefix(idf):
    if idf:
        return f'. "{idf}/export.sh" >/dev/null 2>&1 || {{ echo "export.sh failed"; exit 1; }}; '
    return ""


KNOWN_FAILURES = [
    (r"CFG_TUD_CDC_EP_BUFSIZE.*undeclared|'CFG_TUD_CDC_EP_BUFSIZE' undeclared",
     "esp_tinyusb and tinyusb are from different generations.\n"
     "  The component manager had no dependencies.lock and took the NEWEST tinyusb for an old esp_tinyusb; newer TinyUSB no longer has\n"
     "  CFG_TUD_CDC_EP_BUFSIZE. Espressif pairs esp_tinyusb ~1.0.x with tinyusb ~0.15.x.\n"
     "  1. find who asks for esp_tinyusb:   grep -rn tinyusb <repo>/m5stack --include=idf_component.yml   (not in managed_components/)\n"
     "  2. in that file (m5stack/main/idf_component.yml), next to espressif/esp_tinyusb, add an EXACT old version:\n"
     "       espressif/tinyusb:\n"
     "         version: \"0.15.0~10\"\n"
     "     Registry versions are written number~revision (0.15.0~1 ... 0.15.0~10); '~0.15.10' does not exist and is refused.\n"
     "  3. python3 build_firmware.py --reset-deps    (the bad versions may already be in m5stack/dependencies.lock)\n"
     "  4. python3 build_firmware.py\n"
     "  If upstream's own build instructions ship a dependencies.lock, put THAT file in m5stack/ instead of editing the yml."),
    (r"no versions of (\S+) match (\S+)",
     "The version asked for does not exist in the component registry. Versions are written number~revision (for example 0.15.0~10, 0.21.0~2).\n"
     "  The list is at https://components.espressif.com/components/<namespace>/<name>/versions (for tinyusb: namespace espressif).\n"
     "  Use an exact version from it, e.g.  version: \"0.15.0~10\"."),
    (r"Cannot stat [^\n]*?([\w.\-]+\.py)",
     "The freeze step needs a file that does not exist: the board's manifest.py names it, and nothing created it.\n"
     "  That file is usually GENERATED by another target of the firmware's Makefile (for example the one that packs a release).\n"
     "  1. find who creates it:   grep -rn <file name> <repo>/m5stack --include=Makefile --include=*.mk --include=*.cmake --include=*.py\n"
     "  2. run that step once, or copy the file into m5stack/boards/<base board>/ and build again (the derived board is a copy of that folder).\n"
     "  3. --check now warns about such files before the long build."),
    (r"No space left on device", "The disk is full. A firmware build needs several GB free (ESP-IDF, build folder, managed_components)."),
    (r"quilt: (command )?not found|quilt: nie znaleziono", "quilt is missing:  sudo apt install quilt   (then --setup again)"),
    (r"export\.sh failed", "The ESP-IDF environment could not be loaded: run  python3 build_firmware.py --check  and, if needed, --install-idf."),
    (r"Permission denied.*tty|could not open port", "The serial port is not usable: close Thonny, add yourself to the dialout group (sudo usermod -aG dialout $USER, log in again), "
                                                    "or hold G0 while plugging the cable."),
    (r"Failed to resolve component|Cannot find a version of .* that matches|Could not resolve", "The component manager could not resolve the dependencies (needs a network the first time, and compatible version "
                                                                                                "constraints). The messages above name the component."),
]


def diagnose(text):
    return [advice for pattern, advice in KNOWN_FAILURES if re.search(pattern, text or "", re.S)]


def read_log(path, limit=600_000):
    try:
        with open(path, encoding="utf-8", errors="replace") as f:
            text = f.read()
        return text[-limit:]
    except OSError:
        return ""


def classify_image(path):
    try:
        with open(path, "rb") as f:
            head = f.read(0x8002)
    except OSError:
        return "other"
    if len(head) >= 0x8002 and head[0] == 0xE9 and head[0x8000:0x8002] == b"\xaa\x50":
        return "complete"
    return "partial" if head[:1] == b"\xe9" else "other"


def find_images(m5dir, since):
    out = []
    skip = ("/esp-idf/", "/managed_components/", "/CMakeFiles/", "/bootloader/", "/littlefs", "/.git/")
    for root, dirs, files in os.walk(m5dir):
        dirs[:] = [d for d in dirs if d not in (".git", "CMakeFiles", "managed_components")]
        for name in files:
            if not name.endswith(".bin"):
                continue
            path = os.path.join(root, name)
            if any(s in path + "/" for s in skip):
                continue
            try:
                st = os.stat(path)
            except OSError:
                continue
            if st.st_mtime >= since - 2:
                out.append((path, st.st_size, classify_image(path)))
    rank = {"complete": 0, "partial": 1, "other": 2}
    return sorted(out, key=lambda t: (rank[t[2]], -t[1]))


# ----------------------------------------------------------------------------------------------- the commands

def load_config(args):
    cfg = {}
    p = os.path.join(HERE, "build_config.json")
    if os.path.isfile(p):
        with open(p, encoding="utf-8") as f:
            cfg = json.load(f)
    repo = args.repo or os.environ.get("SQUIRREL_FW_REPO") or cfg.get("repo") or DEFAULT_REPO
    update = getattr(args, "update_repo", False)
    ensure_repo(repo, update=update)
    return dict(repo=repo, idf=args.idf or cfg.get("idf"), base=args.base_board or cfg.get("base_board") or DEFAULT_BASE_BOARD,
                exclude=tuple(cfg.get("exclude", [])) + tuple(args.exclude or ()), prefer=args.prefer or cfg.get("prefer"))


def wrong_folder_hint(app_dir):
    if os.path.isfile(os.path.join(app_dir, "squirrel_app.py")):
        return None
    for root, dirs, files in os.walk(app_dir):
        dirs[:] = [d for d in dirs if d not in EXCLUDE_DIRS and not d.startswith(".")]
        if "squirrel_app.py" in files:
            return (f"squirrel_app.py is not in {app_dir} but in {root}.\n"
                    f"  build_firmware.py takes ITS OWN folder as the folder with the code: move it (and squirrel_boot.py, BUILD.md, device/) to {root}")
    return None


def prepare_sources(app_dir, verbose=True, exclude=(), prefer=None):
    hint = wrong_folder_hint(app_dir)
    if hint:
        raise BuildError(hint)
    sources = find_sources(app_dir, exclude)
    if not sources:
        raise BuildError(f"no .py files found in {app_dir}")
    staged, warnings = layout_for_firmware(sources, prefer)
    errors, more = check_imports(staged)
    if verbose:
        say(f"sources: {len(staged)} modules ({sum(1 for p in staged if p.startswith('screens/'))} of them screens)")
        for w in warnings + more:
            say("  warning: " + w)
        for e in errors:
            say("  ERROR: " + e)
    if errors:
        raise BuildError("the sources do not hang together (see ERROR lines above)")
    if "squirrel_boot.py" not in staged:
        raise BuildError("squirrel_boot.py is missing from the folder: /flash/main.py needs it")
    if "squirrel_app.py" not in staged:
        raise BuildError("squirrel_app.py is missing from the folder")
    return staged


def cmd_check(args):
    c = load_config(args)
    problems = 0
    say(f"app folder : {HERE}")
    try:
        staged = prepare_sources(HERE, exclude=c["exclude"], prefer=c["prefer"])
    except BuildError as e:
        say("  " + str(e))
        problems += 1
        staged = {}
    try:
        repo = locate_repo(c["repo"])
        say(f"firmware   : {repo}  (git {git_short(repo) or '?'})")
    except BuildError as e:
        say("firmware   : " + str(e))
        return 1
    base = os.path.join(repo, "m5stack", "boards", c["base"])
    say(f"base board : {c['base']}  " + ("found" if os.path.isdir(base) else "MISSING"))
    if os.path.isdir(base):
        say("  manifest.py: " + ("found" if os.path.isfile(os.path.join(base, "manifest.py")) else "MISSING"))
        if not os.path.isfile(os.path.join(base, "manifest.py")):
            problems += 1
    else:
        problems += 1
        boards = os.path.join(repo, "m5stack", "boards")
        say("  boards here: " + (", ".join(sorted(d for d in os.listdir(boards) if "ardputer" in d)) or "-"))
    derived = os.path.join(repo, "m5stack", "boards", c["base"] + BOARD_SUFFIX)
    if os.path.exists(derived):
        say(f"derived    : {os.path.basename(derived)} exists " + ("(made by this tool)" if os.path.exists(os.path.join(derived, GENERATED_MARK)) else "(NOT made by this tool - will refuse to overwrite)"))
    found = [(p, idf_version(p)) for p in idf_candidates(repo, c["idf"])]
    if found:
        for p, v in found:
            say(f"ESP-IDF    : {p}  {v or '(version unknown)'}  " + ("<- usable" if idf_ok(v) else "(not 5.4.x: not used)"))
    if not any(idf_ok(v) for _p, v in found):
        say("ESP-IDF    : no 5.4.x found - run  python3 build_firmware.py --install-idf" if not found else
            "ESP-IDF    : none of them is 5.4.x - run  python3 build_firmware.py --install-idf")
        problems += 1
    mc = find_mpy_cross(repo)
    say("mpy-cross   : " + (mc if mc else "not built yet - run  --build-mpy-cross  (gcc only; --setup does it too, with ESP-IDF and quilt)"))
    if not mc:
        problems += 1
    mk = os.path.join(repo, "micropython", "py")
    say("submodules  : " + ("micropython present" if os.path.isdir(mk) and os.listdir(mk) else "micropython EMPTY - run  --setup"))
    tools = ", ".join(f"{t}={'yes' if shutil.which(t) else 'NO'}" for t in ("make", "bash", "git", "python3", "quilt"))
    say("tools       : " + tools)
    if not shutil.which("quilt"):
        say("  quilt is missing: `make patch` needs it ->  sudo apt install quilt")
        problems += 1
    say("\n" + ("everything needed is in place" if not problems else f"{problems} thing(s) to fix before a build"))
    return 1 if problems else 0


def cmd_setup(args):
    c = load_config(args)
    repo = locate_repo(c["repo"])
    idf, version = choose_idf(repo, c["idf"], allow_any=False)
    if not shutil.which("quilt"):
        raise BuildError("quilt is not installed - `make patch` needs it:  sudo apt install quilt")
    marker = os.path.join(STATE, "setup.done")
    if os.path.exists(marker) and not args.force:
        say("setup was already done here (.build/setup.done). Use --force to repeat it.")
        return 0
    os.makedirs(STATE, exist_ok=True)
    say(f"using ESP-IDF {version} at {idf}")
    m5 = os.path.join(repo, "m5stack")
    for target in ("submodules", "patch", "littlefs", "mpy-cross"):
        say(f"== make {target}")
        if bash(idf_prefix(idf) + f"make {target}", cwd=m5) != 0:
            raise BuildError(f"`make {target}` failed. If it says a patch is already applied, the setup was done before: "
                             f"run the remaining targets by hand, then  touch {marker}")
    open(marker, "w").write(time.strftime("%Y-%m-%d %H:%M:%S\n"))
    say("setup done")
    return 0


def cmd_build_mpy_cross(args):
    c = load_config(args)
    repo = locate_repo(c["repo"])
    src = os.path.join(repo, "micropython", "mpy-cross")
    if not os.path.isdir(src) or not os.listdir(src):
        raise BuildError(f"{src} is empty: the submodule is missing. Run  git submodule update --init micropython  in {repo} (or --setup).")
    if not shutil.which("gcc") and not shutil.which("cc"):
        raise BuildError("no C compiler: sudo apt install build-essential")
    say(f"== make -C {src}   (only a C compiler is needed: no ESP-IDF, no quilt)")
    if bash(f'make -C "{src}"') != 0:
        raise BuildError("building mpy-cross failed (see above)")
    mc = find_mpy_cross(repo)
    if not mc:
        raise BuildError(f"make finished, but there is no mpy-cross binary in {src}/build")
    say(f"mpy-cross is at {mc}")
    say("Note: this one is built from the firmware's MicroPython WITHOUT the patches that --setup applies. The .mpy format is the same "
        "in practice; if the device ever says 'incompatible .mpy file', do the full --setup.")
    return 0


def cmd_install_idf(args):
    dest = os.path.abspath(os.path.expanduser(args.install_idf))
    resume = os.path.isdir(os.path.join(dest, ".git"))
    if os.path.exists(dest) and os.listdir(dest) and not resume:
        raise BuildError(f"{dest} already exists and is not empty. Use --install-idf <another folder>, or --idf {dest} if it is the right one.")
    steps = []
    if resume:
        say(f"{dest} holds an earlier, unfinished installation: continuing it (what was downloaded is kept)")
    else:
        say(f"installing ESP-IDF {IDF_WANTED} into {dest}")
        steps.append(f'git clone --depth 1 --branch {IDF_WANTED} {IDF_URL} "{dest}"')
    steps.append(f'git -C "{dest}" submodule update --init --recursive --depth 1 --jobs 4 --progress')
    steps.append(f'cd "{dest}" && ./install.sh esp32s3')
    say("(a few hundred MB to 1-2 GB; the big libraries take minutes each. To see that it is alive: "
        f"`du -sh {dest}/.git/modules` in another terminal keeps growing. Ctrl-C is safe: run the same command again to continue)")
    for step in steps:
        if bash(step) != 0:
            raise BuildError(f"this step failed: {step}\n  Run the same command again: it continues where it stopped.")
    say(f"done. It is found automatically next time (or use --idf {dest}).")
    return 0


def cmd_stage_only(args):
    c = load_config(args)
    staged = prepare_sources(HERE, exclude=c["exclude"], prefer=c["prefer"])
    build_id = time.strftime("%Y%m%d-%H%M")
    stage_dir = os.path.join(STATE, "stage")
    files = stage(staged, stage_dir, build_id, HERE)
    say(f"staged {len(files)} modules + sq_info.py in {stage_dir}")
    try:
        mc = find_mpy_cross(locate_repo(c["repo"]))
    except BuildError:
        mc = shutil.which("mpy-cross")
    if not mc:
        say("mpy-cross not found: the sources were collected and their imports checked, but NOT compiled (run --setup)")
        return 0
    errors, total = compile_check(mc, stage_dir)
    for e in errors:
        say("  ERROR: " + e)
    if errors:
        raise BuildError(f"{len(errors)} file(s) do not compile with the firmware's mpy-cross")
    say(f"all modules compile with {mc}  (bytecode in all: {total} bytes)")
    return 0


def cmd_mpy(args):
    c = load_config(args)
    staged = prepare_sources(HERE, exclude=c["exclude"], prefer=c["prefer"])
    stage_dir = os.path.join(STATE, "stage")
    stage(staged, stage_dir, time.strftime("%Y%m%d-%H%M"), HERE)
    mc = find_mpy_cross(locate_repo(c["repo"]))
    if not mc:
        raise BuildError("mpy-cross not found. The quick way (gcc only):  python3 build_firmware.py --build-mpy-cross\n"
                         "  (the full way: --setup, which also needs ESP-IDF 5.4.x and quilt)")
    out = os.path.join(DIST, "mpy")
    errors, total = compile_check(mc, stage_dir, keep_dir=out)
    for e in errors:
        say("  ERROR: " + e)
    if errors:
        raise BuildError("compilation failed")
    say(f"compiled to {out}  ({total} bytes). Upload the tree to /flash/apps/Squirrel (screens/ included);"
        f" a stale .mpy hides a newer .py - delete old ones first.")
    return 0


def cmd_reset_deps(args):
    c = load_config(args)
    repo = locate_repo(c["repo"])
    m5 = os.path.join(repo, "m5stack")
    lock = os.path.join(m5, "dependencies.lock")
    tracked = subprocess.run(["git", "-C", repo, "ls-files", "--error-unmatch", "m5stack/dependencies.lock"], capture_output=True).returncode == 0
    if tracked:
        raise BuildError("m5stack/dependencies.lock is part of the repository (git tracks it): it was put there on purpose, so it is not deleted.\n"
                         "  `git -C " + repo + " checkout -- m5stack/dependencies.lock` restores it if the build changed it.")
    removed = []
    for path in (lock, os.path.join(m5, "managed_components")):
        if os.path.isdir(path):
            shutil.rmtree(path)
            removed.append(path)
        elif os.path.isfile(path):
            os.remove(path)
            removed.append(path)
    build = os.path.join(m5, "build-" + c["base"] + BOARD_SUFFIX)
    if os.path.isdir(build):
        shutil.rmtree(build)
        removed.append(build)
    for r in removed:
        say("removed " + r)
    say("nothing to remove" if not removed else "the next build resolves the ESP-IDF components again (needs a network)")
    return 0


def cmd_diagnose(args):
    text = read_log(os.path.join(STATE, "make.log"))
    if not text:
        raise BuildError("there is no .build/make.log yet: run a build first")
    hints = diagnose(text)
    say("\n".join("- " + h for h in hints) if hints else "No known problem found in the last build log (.build/make.log). Look at its end for the first 'error'.")
    return 0


def cmd_clean(args):
    c = load_config(args)
    for p in (STATE,):
        if os.path.isdir(p):
            shutil.rmtree(p)
            say("removed " + p)
    try:
        repo = locate_repo(c["repo"])
        derived = os.path.join(repo, "m5stack", "boards", c["base"] + BOARD_SUFFIX)
        if os.path.exists(os.path.join(derived, GENERATED_MARK)):
            shutil.rmtree(derived)
            say("removed " + derived)
            build = os.path.join(repo, "m5stack", "build-" + c["base"] + BOARD_SUFFIX)
            if os.path.isdir(build):
                shutil.rmtree(build)
                say("removed " + build)
    except BuildError:
        pass
    return 0


def font_into_image(repo):
    """Copy the app's font where `make` packs the system file system.  Returns the copy (removed after the build),
    or None: no font here, or a file of that name is already there (then it is left alone and used)."""
    font = find_font(HERE)
    if font is None:
        say("font       : none found (fonts/" + FONT_NAME + " or " + FONT_NAME + ") - the image has no Polish letters")
        return None
    folder = os.path.join(repo, *FONT_IN_REPO)
    target = os.path.join(folder, FONT_NAME)
    if os.path.exists(target):
        say(f"font       : {target} already exists - packed as it is")
        return None
    os.makedirs(folder, exist_ok=True)
    shutil.copyfile(font, target)
    say(f"font       : {os.path.relpath(font, HERE)} ({os.path.getsize(font)} bytes) goes into the image -> {FONT_ON_DEVICE}")
    return target


def cmd_build(args):
    c = load_config(args)
    repo = locate_repo(c["repo"])
    new_board = c["base"] + BOARD_SUFFIX
    staged = prepare_sources(HERE, exclude=c["exclude"], prefer=c["prefer"])
    build_id = time.strftime("%Y%m%d-%H%M")
    stage_dir = os.path.join(STATE, "stage")
    files = stage(staged, stage_dir, build_id, HERE)

    mc = find_mpy_cross(repo)
    if not mc:
        raise BuildError("mpy-cross is not built, so the setup of the firmware repository is not complete: run  python3 build_firmware.py --setup")
    errors, total = compile_check(mc, stage_dir)
    for e in errors:
        say("  ERROR: " + e)
    if errors:
        raise BuildError("fix the files above first: they do not compile with the firmware's mpy-cross")
    say(f"mpy-cross: all {len(files)} modules compile ({total} bytes of bytecode)")

    idf, version = choose_idf(repo, c["idf"], allow_any=args.allow_any_idf)
    say(f"ESP-IDF {version or '?'} at {idf}")

    btype = board_type(os.path.join(repo, "m5stack", "Makefile"), c["base"])
    type_arg = f" BOARD_TYPE={btype}" if btype else ""
    made, failed, _elsewhere = generate_missing(repo, c["base"], idf, type_arg)
    if failed and not args.allow_missing:
        raise BuildError("The manifest of " + c["base"] + " names " + ", ".join(failed) + ", and `make` could not make it (its own message is above).\n"
                         "  The build would stop at the freeze step, half an hour from now, with 'Cannot stat'. So it stops here.\n"
                         "  1. read how the Makefile makes it:   grep -n -B2 -A8 " + os.path.splitext(failed[0])[0] + " " + os.path.join(repo, "m5stack", "Makefile") + "\n"
                         "     and the script it calls (for firmware_info.py: m5stack/scripts/gen-firmware-info.sh). It takes the version from a git TAG:\n"
                         "     `git -C " + repo + " describe --tags` must work; if it does not:  git -C " + repo + " fetch --tags\n"
                         "  2. or run it by hand:   cd " + os.path.join(repo, "m5stack") + " && make BOARD=" + c["base"] + " boards/" + c["base"] + "/" + failed[0] + "\n"
                         "  3. or put the file there yourself, then run this tool again (--allow-missing skips this check).")
    dst = make_board(repo, c["base"], new_board, stage_dir)
    say(f"board {new_board} written to {dst}")
    for ref in manifest_missing_files(dst, repo):
        say(f"  WARNING: the board's manifest.py names {ref}, which does not exist, and the Makefile could not make it.\n"
            f"    The build will stop at the freeze step with 'Cannot stat'.\n"
            f"    Find who creates it:  grep -rn {os.path.basename(ref)} {os.path.join(repo, 'm5stack')} --include=Makefile --include=*.mk --include=*.cmake --include=*.sh")
    if not args.no_exclude and git_exclude(repo, new_board):
        say("  (added to .git/info/exclude: it stays out of `git status`)")

    m5 = os.path.join(repo, "m5stack")
    build_dir = os.path.join(m5, "build-" + new_board)
    last = os.path.join(STATE, "last_idf")
    previous = open(last).read().strip() if os.path.exists(last) else None
    if os.path.isdir(build_dir) and previous != (version or idf):
        shutil.rmtree(build_dir)
        say(f"removed the old build folder (it was made with {previous or 'an unknown ESP-IDF'}, this build uses {version or idf})")
    os.makedirs(STATE, exist_ok=True)
    open(last, "w").write(version or idf)

    started = time.time()
    say(f"== make BOARD={new_board} {args.target}   (this takes a while)")
    log_path = os.path.join(STATE, "make.log")
    if btype:
        say(f"board type {btype} (taken over from {c['base']}: the Makefile derives it from the board's name)")
    if args.target == "pack_all":
        say("  note: pack_all also writes an EMPTY user file system over /flash: main.py is gone and has to be uploaded again")
    font_copy = font_into_image(repo)
    try:
        code = bash(idf_prefix(idf) + f'set -o pipefail; make BOARD={new_board}{type_arg} {args.target} 2>&1 | tee "{log_path}"', cwd=m5)
    finally:
        if font_copy:
            os.remove(font_copy)              # the firmware repository is left as it was
    if code != 0:
        hints = diagnose(read_log(log_path))
        extra = ("\n\nWhat this looks like:\n- " + "\n- ".join(hints)) if hints else ""
        raise BuildError(f"the build failed (exit {code}). The messages above say why; the sources were already checked, so look for a firmware/IDF problem."
                         f"{extra}\n  (the whole output is in {log_path}; --diagnose explains it again)")

    images = find_images(m5, started)
    if not images:
        raise BuildError("the build finished but no new .bin was found under m5stack/. Look in the build folder by hand (build-*/).")
    say("images written by this build:")
    for path, size, kind in images:
        say(f"  {kind:9s} {size:9d}  {os.path.relpath(path, repo)}")
    best = images[0]
    os.makedirs(DIST, exist_ok=True)
    name = f"squirrel-{new_board}-{git_short(repo) or 'nogit'}-{build_id}.bin"
    target = os.path.join(DIST, name)
    shutil.copyfile(best[0], target)
    with open(os.path.join(DIST, name[:-4] + ".txt"), "w", encoding="utf-8") as f:
        f.write(f"build {build_id}\nboard {new_board}\nfirmware git {git_short(repo)}\nesp-idf {version}\nimage kind {best[2]}\n"
                + "".join(f"{p}  {s}  {c:08x}\n" for p, s, c in files))
    say(f"\n==> {target}  ({best[1]} bytes, {best[2]} image)")
    if best[2] == "complete":
        say("flash:  esptool.py --chip esp32s3 -b 460800 write_flash 0x0 " + name + "   (or: build_firmware.py --flash PORT)")
    else:
        say("This is NOT a complete image (no partition table at 0x8000): do not write it at 0x0.\n"
            "Flash through the firmware's own target:  cd m5stack && make BOARD=" + new_board + " flash")
    if args.flash:
        return flash(target, best[2], args.flash, idf)
    return 0


FLASH_WARNING = """  Before you flash, know what the image does (it is the whole flash from 0x0):
    - the system file system is written again, and the NVS partition (UIFlow's settings, for example the Wi-Fi it saved) is replaced;
    - files you uploaded to /flash may be gone afterwards: upload /flash/main.py (device/main.py) again
      (the font is inside the image, at /system/common/font/squirrel.vlw; the settings, notes and everything else of the app
      are on the SD card and are not touched);
    - close Thonny (it holds the port).  esptool usually gets the device into download mode by itself; if it cannot connect,
      hold G0 while plugging in the USB cable (or press reset while holding G0), then let go.  After writing, the device is
      restarted by its watchdog and starts the new firmware on its own."""


def wait_for_port(port, seconds=15):
    """Wait until the serial port exists again (an S3 re-appears on USB after a reset).  True if it does."""
    for _ in range(seconds * 2):
        if os.path.exists(port):
            return True
        time.sleep(0.5)
    return os.path.exists(port)


def flash(image, kind, port, idf):
    if kind != "complete":
        raise BuildError("refusing to flash: this is not a complete image (see above)")
    say(FLASH_WARNING)
    where = f'-p "{port}" ' if port else ""
    say(f"== flashing {image}" + (f" to {port}" if port else " (esptool looks for the port itself)"))
    # --before no_reset first: a device already in download mode (G0 held while plugging in) must NOT be reset - the
    # reset makes it leave download mode, its USB port vanishes for a moment and esptool cannot open it.  Only if that
    # finds no bootloader (the app is running) is the usual reset into download mode tried.
    # --after watchdog_reset: the usual reset through RTS leaves an S3 on its USB-Serial/JTAG port in the bootloader
    # ("waiting for download"); a reset by the RTC watchdog starts the new firmware.
    base = idf_prefix(idf) + f'python -m esptool --chip esp32s3 {where}-b 460800 --after watchdog_reset'
    code = bash(f'{base} --before no_reset write_flash 0x0 "{image}"')
    if code != 0:
        say("  no bootloader answered without a reset (the app is running?) - trying again with a reset into download mode")
        if port:
            wait_for_port(port)
        code = bash(f'{base} --before default_reset write_flash 0x0 "{image}"')
    if code != 0:
        raise BuildError("flashing failed. Close Thonny (it holds the port); hold G0 while plugging the USB cable to enter the bootloader;\n"
                         "  if the port is refused: sudo usermod -aG dialout $USER and log in again.")
    say("flashed. If /flash/main.py is missing, upload it (device/main.py) with Thonny, then check:  import sq_info; sq_info.report()")
    return 0


def cmd_flash_image(args):
    c = load_config(args)
    path = args.flash_image
    if not os.path.isfile(path) and os.path.isfile(os.path.join(DIST, path)):
        path = os.path.join(DIST, path)
    if not os.path.isfile(path):
        raise BuildError(f"{args.flash_image} not found (looked in the current folder and in {DIST})")
    path = os.path.abspath(path)
    kind = classify_image(path)
    say(f"image {path}: {os.path.getsize(path)} bytes, {kind}")
    repo = locate_repo(c["repo"])
    idf, _version = choose_idf(repo, c["idf"], allow_any=True)
    return flash(path, kind, args.flash, idf)


def main(argv=None):
    ap = argparse.ArgumentParser(description="Build the Squirrel! firmware with the app frozen into it.", formatter_class=argparse.RawDescriptionHelpFormatter, epilog=__doc__)
    ap.add_argument("--repo", help=f"firmware repository (default: vendor/cardputer-adv-micropython, cloned automatically)")
    ap.add_argument("--idf", help="ESP-IDF folder (the one with export.sh)")
    ap.add_argument("--base-board", help=f"board to copy (default {DEFAULT_BASE_BOARD})")
    ap.add_argument("--check", action="store_true", help="report what is in place; change nothing")
    ap.add_argument("--setup", action="store_true", help="run submodules/patch/littlefs/mpy-cross once")
    ap.add_argument("--build-mpy-cross", action="store_true", help="build the repository's mpy-cross with gcc only (no ESP-IDF needed)")
    ap.add_argument("--install-idf", nargs="?", const="~/esp-idf-" + IDF_WANTED, metavar="DIR", help=f"clone and install ESP-IDF {IDF_WANTED} (default folder ~/esp-idf-{IDF_WANTED})")
    ap.add_argument("--allow-any-idf", action="store_true", help="build even with an ESP-IDF that is not 5.4.x (not for --setup)")
    ap.add_argument("--exclude", action="append", metavar="FILE", help="leave this file out of the firmware (repeatable)")
    ap.add_argument("--prefer", choices=("newer", "flat", "screens"), help="which copy to freeze when a screen module exists twice with different content")
    ap.add_argument("--force", action="store_true", help="with --setup: repeat it")
    ap.add_argument("--stage-only", action="store_true", help="collect and compile-check the sources; no firmware")
    ap.add_argument("--mpy", action="store_true", help="compile the modules to dist/mpy/ (no firmware)")
    ap.add_argument("--update-repo", action="store_true", help="pull the latest changes in vendor/cardputer-adv-micropython before building")
    ap.add_argument("--clean", action="store_true", help="remove .build/ and the generated board")
    ap.add_argument("--reset-deps", action="store_true", help="delete dependencies.lock and managed_components of the firmware repository (re-resolved by the next build)")
    ap.add_argument("--diagnose", action="store_true", help="explain the last failed build from .build/make.log")
    ap.add_argument("--target", choices=("pack", "build", "pack_all"), default="pack",
                    help="make target: pack = a complete image without the user file system (default); build = the application only; "
                         "pack_all = also an empty user file system (erases /flash)")
    ap.add_argument("--flash-image", metavar="FILE", help="flash an image that is already built (a file name from dist/ is enough); with --flash PORT to name the port")
    ap.add_argument("--flash", metavar="PORT", help="after the build, flash a complete image to PORT")
    ap.add_argument("--allow-missing", action="store_true", help="build even if a file named by the base board's manifest could not be made")
    ap.add_argument("--no-exclude", action="store_true", help="do not touch .git/info/exclude of the firmware repo")
    args = ap.parse_args(argv)
    try:
        if args.check:
            return cmd_check(args)
        if args.flash_image:
            return cmd_flash_image(args)
        if args.build_mpy_cross:
            return cmd_build_mpy_cross(args)
        if args.install_idf:
            return cmd_install_idf(args)
        if args.setup:
            return cmd_setup(args)
        if args.stage_only:
            return cmd_stage_only(args)
        if args.mpy:
            return cmd_mpy(args)
        if args.reset_deps:
            return cmd_reset_deps(args)
        if args.diagnose:
            return cmd_diagnose(args)
        if args.clean:
            return cmd_clean(args)
        return cmd_build(args)
    except BuildError as e:
        say("\nERROR: " + str(e))
        return 1


if __name__ == "__main__":
    sys.exit(main())