# port_config.py - the port this firmware is built for: M5Stack Cardputer ADV
#
# GENERATED by build_firmware.py from ports/cardputer_adv/port.toml and features.toml - do not edit; after a change
# there:  python3 build_firmware.py --gen-port-config [--port NAME]   (a build regenerates it by itself)

PORT = 'cardputer_adv'
BOARD_MODULE = 'ports.cardputer_adv.board'
HARDWARE = frozenset(('audio_in', 'audio_out', 'buttons', 'buttons.quick', 'clock', 'display', 'i2c', 'i2c.sys', 'input', 'input.keyboard', 'motion', 'power', 'radio', 'radio.wifi', 'signal', 'signal.buzzer', 'signal.led', 'storage', 'storage.removable', ))
FEATURES = frozenset(('buzzer', 'hw_clock', 'key_calibration', 'led', 'text_edit', 'voice_notes', 'wifi_ntp', ))
# what the app hides because a feature is not built (features.toml)
HIDDEN_MENUS = frozenset(())
HIDDEN_SCREENS = frozenset(())
HIDDEN_ACTIONS = frozenset(())
HIDDEN_GROUPS = frozenset(())


PORT_NAME = 'cardputer_adv'
PORT_TITLE = 'M5Stack Cardputer ADV'
PORT_MCU = 'esp32s3'
PORT_FIRMWARE = 'cardputer-adv-micropython'
PORT_BOARD = 'M5STACK_CardputerADV_Custom'
PORT_IDF = 'v5.4.2'
PORT_MACHINE = 'Cardputer-ADV'

DISPLAY_DRIVER = 'm5_display'
DISPLAY_WIDTH = 240
DISPLAY_HEIGHT = 135
DISPLAY_FONTS = 'vlw'

I2C_SYS_ID = 0
I2C_SYS_SDA = 8
I2C_SYS_SCL = 9
I2C_SYS_FREQ = 400000

INPUT_DRIVER = 'tca8418_keypad'
INPUT_KEYBOARD = True
INPUT_BUS = 'sys'
INPUT_ADDR = 52
INPUT_INT = 11

BUTTONS_QUICK_DRIVER = 'gpio_button'
BUTTONS_QUICK_PIN = 0

STORAGE_DRIVER = 'sd_spi'
STORAGE_REMOVABLE = True
STORAGE_SLOT = 3
STORAGE_WIDTH = 1
STORAGE_SCK = 40
STORAGE_MISO = 39
STORAGE_MOSI = 14
STORAGE_CS = 12
STORAGE_FREQ = 1000000
STORAGE_BASE_DIR = '/sd/Squirrel'
STORAGE_FLASH_ROOT = '/flash'

CLOCK_DRIVER = 'ds1302'
CLOCK_CLK = 6
CLOCK_DAT = 4
CLOCK_RST = 3

POWER_DRIVER = 'm5_power'

AUDIO_OUT_DRIVER = 'm5_audio'
AUDIO_IN_DRIVER = 'm5_audio'

SIGNAL_LED_DRIVER = 'ws2812'
SIGNAL_LED_PIN = 21
SIGNAL_LED_MIN_BACKLIGHT = 255
SIGNAL_LED_MAX_SUM = 228
SIGNAL_BUZZER_DRIVER = 'pin_pulser'
SIGNAL_BUZZER_INSTALLED = True
SIGNAL_BUZZER_PIN = 13
SIGNAL_BUZZER_PWM_FREQ = 0

MOTION_DRIVER = 'bmi270'
MOTION_BUS = 'sys'
MOTION_ADDRS = (105, 104)

RADIO_WIFI = True

POWER_MGMT_WAKE_PINS = (0, 11)
POWER_MGMT_SLOW_CPU_HZ = 80000000
